Repository CA-G12/e-commerce-team-7, pull requests merged in 2022-09, with the labels that each got.

#2 complete intial file structure
  .eslintrc.js
  .github/workflows/node.js.yml
  .prettierrc.json
  .vscode/settings.json
  client/.eslintrc.js
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.jsx
  client/src/Components/.gitkeep
  client/src/index.css
  client/src/index.jsx
  package-lock.json
  package.json
  src/app.js
  src/controllers/auth/index.js
  src/controllers/auth/login.js
  src/controllers/auth/logout.js
  src/controllers/auth/signup.js
  src/controllers/cart/deleteCart.js
  src/controllers/cart/getCart.js
  src/controllers/cart/index.js
  src/controllers/cart/postCart.js
  src/controllers/index.js
  src/controllers/product/getProduct.js
  src/controllers/product/index.js
  src/database/config/build.js
  src/database/config/connection.js
  src/database/config/schema.sql
  src/database/config/seeds.sql
  src/database/queries/cart/.gitkeep
  src/database/queries/index.js
  src/database/queries/products/.gitkeep
  src/database/queries/users/.gitkeep
  src/index.js
  src/routes/auth.js
  src/routes/cart.js
  src/routes/index.js
  src/routes/product.js
  src/tests/cart.test.js
  src/tests/product.test.js
  src/tests/user.test.js
Labels: Await Review

#3 fix node version in the package.json file
  package.json
Labels: Await Review

#10 8 handle products
  .eslintrc.js
  .example.env
  package-lock.json
  package.json
  src/controllers/index.js
  src/controllers/product/getProduct.js
  src/controllers/product/index.js
  src/database/config/build.js
  src/database/config/connection.js
  src/database/queries/index.js
  src/database/queries/products/.gitkeep
  src/database/queries/products/getProudctsQuery.js
  src/database/queries/products/index.js
  src/routes/index.js
  src/routes/product.js
  src/tests/product.test.js
  src/tests/user.test.js
Labels: Await Review

#14 13 verify access token
  .eslintrc.js
  .vscode/settings.json
  src/middleware/verifyAccessToken.js
Labels: Await Review

#17 9 handle cart endpoints
  package.json
  src/controllers/cart/deleteCart.js
  src/controllers/cart/getCart.js
  src/controllers/cart/index.js
  src/controllers/cart/postCart.js
  src/controllers/cart/updateCart.js
  src/controllers/index.js
  src/database/queries/cart/.gitkeep
  src/database/queries/cart/addCart.js
  src/database/queries/cart/deleteCart.js
  src/database/queries/cart/getCart.js
  src/database/queries/cart/index.js
  src/database/queries/cart/updateCart.js
  src/database/queries/index.js
  src/routes/cart.js
  src/tests/cart.test.js
  src/tests/product.test.js
Labels: Approved

#18 12 handle authenticion
  src/controllers/auth/index.js
  src/controllers/auth/signup.js
  src/controllers/index.js
  src/database/queries/index.js
  src/database/queries/users/getUsername.js
  src/database/queries/users/index.js
  src/database/queries/users/signUp.js
  src/routes/auth.js
  src/tests/user.test.js
  src/utils/generateToken.js
  src/utils/validation/index.js
  src/utils/validation/signup.js
Labels: Await Review

#22 login and logout routers
  src/controllers/auth/index.js
  src/controllers/auth/login.js
  src/controllers/auth/logout.js
  src/controllers/auth/signup.js
  src/controllers/index.js
  src/database/queries/users/getUser.js
  src/database/queries/users/index.js
  src/routes/auth.js
  src/tests/user.test.js
  src/utils/validation/index.js
  src/utils/validation/login.js
Labels: Await Review

#21 9 handle cart endpoints
  src/controllers/cart/deleteCart.js
  src/controllers/cart/postCart.js
  src/database/config/seeds.sql
  src/database/queries/cart/getCart.js
  src/database/queries/cart/updateCart.js
  src/routes/index.js
  src/tests/cart.test.js
Labels: Approved

#23 12 handle authenticion
  src/tests/user.test.js
Labels: Approved

#25 Complete react file structure
  client/src/App.css
  client/src/App.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Header/style.css
  client/src/Components/LandingCard/LandingCard.jsx
  client/src/Components/LandingCard/style.css
  client/src/Components/ProductCard/ProductCard.jsx
  client/src/Components/ProductCard/style.css
  client/src/Components/ProductsPage/ProductsPage.jsx
  client/src/Components/ProductsPage/style.css
  client/src/Components/SingleProduct/SingleProduct.jsx
  client/src/Components/SingleProduct/style.css
  client/src/Components/index.jsx
  client/src/index.css
  client/src/index.jsx
Labels: Approved

#30 complete single product compontent
  client/src/Components/.gitkeep
  client/src/Components/SingleProduct/SingleProduct.jsx
  client/src/Components/SingleProduct/style.css
Labels: Await Review

#29 create landing card
  client/src/App.css
  client/src/Components/LandingCard/LandingCard.jsx
  client/src/Components/LandingCard/img/product.png
  client/src/Components/LandingCard/style.css
  src/tests/user.test.js
Labels: Await Review

#32 26 header component
  .vscode/settings.json
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Header/style.css
  client/src/Components/SingleProduct/style.css
Labels: Await Review

#35 34 product component
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/Components/ProductCard/Card.jsx
  client/src/Components/ProductCard/ProductCard.jsx
  client/src/Components/ProductCard/fetch.js
  client/src/Components/ProductCard/style.css
  src/tests/cart.test.js
Labels: Approved

#37 add svg element for product container
  client/src/App.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/LandingCard/LandingCard.jsx
  client/src/Components/ProductCard/Card.jsx
  client/src/Components/ProductCard/ProductCard.jsx
  client/src/Components/ProductCard/style.css
Labels: Approved

#40 fix the style for productCard component
  .eslintrc.js
  client/.eslintrc.js
  client/src/App.css
  client/src/Components/ProductCard/Card.jsx
  client/src/Components/ProductCard/ProductCard.jsx
  client/src/Components/ProductCard/style.css
  src/database/config/seeds.sql
Labels: Approved

#46 Create functions for filtering
  .eslintrc.js
  .gitignore
  .prettierrc.json
  client/.eslintrc.js
  client/public/index.html
  src/controllers/index.js
  src/controllers/product/filterByCategory.js
  src/controllers/product/filterByPrice.js
  src/controllers/product/getAllCategories.js
  src/controllers/product/index.js
  src/database/queries/index.js
  src/database/queries/products/filterCategory.js
  src/database/queries/products/filterPrice.js
  src/database/queries/products/getCategory.js
  src/database/queries/products/index.js
  src/routes/product.js
  src/tests/product.test.js
Labels: Await Review

#48 change the fetch to axios
  .eslintrc.js
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/ProductCart.jsx
  client/src/Components/ProductCard/fetch.js
  client/src/Components/index.jsx
Labels: Await Review

#50 42 products page
  .prettierrc.json
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/ProductCart.jsx
  client/src/Components/Header/style.css
  client/src/Components/LandingCard/style.css
  client/src/Components/ProductCard/fetch.js
  client/src/Components/ProductCard/style.css
  client/src/Components/ProductsPage/ProductsPage.jsx
  client/src/Components/ProductsPage/style.css
  client/src/Components/SingleProduct/style.css
  client/src/Components/index.jsx
  package-lock.json
  package.json
  src/controllers/auth/index.js
  src/controllers/auth/logout.js
  src/controllers/cart/deleteCart.js
  src/controllers/cart/getCart.js
  src/controllers/cart/postCart.js
  src/controllers/cart/updateCart.js
  src/controllers/index.js
  src/controllers/product/filterByCategory.js
  src/controllers/product/filterByPrice.js
  src/controllers/product/getAllCategories.js
  src/controllers/product/getCount.js
  src/controllers/product/getProduct.js
  src/controllers/product/index.js
  src/database/config/build.js
  src/database/config/jsonToSqlScript.js
  src/database/config/seedsData.json
  src/database/queries/cart/updateCart.js
  src/database/queries/index.js
  src/database/queries/products/filterCategory.js
  src/database/queries/products/getCategory.js
  src/database/queries/products/getCount.js
  src/database/queries/products/getProudctsQuery.js
  src/database/queries/products/index.js
  src/database/queries/users/getUser.js
  src/database/queries/users/getUsername.js
  src/database/queries/users/index.js
  src/error/customizedError.js
  src/error/handleError.js
  src/index.js
  src/middleware/verifyAccessToken.js
  src/routes/index.js
  src/routes/product.js
  src/tests/cart.test.js
  src/tests/product.test.js
  src/tests/user.test.js
  src/utils/validation/index.js
  src/utils/validation/login.js
  src/utils/validation/signup.js
Labels: Await Review

#45 complete auth components
  .eslintrc.js
  client/src/App.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Login/Login.jsx
  client/src/Components/Login/style.css
  client/src/Components/Signup/Singup.jsx
  client/src/Components/Signup/style.css
  client/src/Components/index.jsx
Labels: Await Review

#52 42 products page
  client/src/Components/Login/style.css
  client/src/Components/ProductCard/fetch.js
  client/src/Components/ProductsPage/ProductsPage.jsx
  client/src/Components/Signup/style.css
  src/controllers/index.js
  src/controllers/product/getAllProducts.js
  src/controllers/product/getCount.js
  src/controllers/product/index.js
  src/database/queries/index.js
  src/database/queries/products/getCount.js
  src/database/queries/products/getFilteredProducts.js
  src/database/queries/products/index.js
  src/routes/product.js
Labels: Await Review

#55 Fix bugs #53
  client/src/App.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Login/Login.jsx
  client/src/Components/Signup/Singup.jsx
  src/controllers/auth/verify.js
  src/routes/auth.js
  src/tests/user.test.js
Labels: Await Review

#58 56 sigle page
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/ProductCart.jsx
  client/src/Components/LandingCard/style.css
  client/src/Components/Login/Login.jsx
  client/src/Components/ProductCard/Card.jsx
  client/src/Components/ProductsPage/ProductsPage.jsx
  client/src/Components/Signup/Singup.jsx
  client/src/Components/SingleProduct/SingleProduct.jsx
  client/src/Components/SingleProduct/style.css
  src/controllers/auth/login.js
  src/controllers/cart/deleteCart.js
  src/controllers/index.js
  src/controllers/product/getProductById.js
  src/controllers/product/index.js
  src/database/queries/index.js
  src/database/queries/products/getProductByIdQuery.js
  src/database/queries/products/index.js
  src/routes/cart.js
  src/routes/product.js
  src/tests/cart.test.js
  src/tests/user.test.js
Labels: Done

#59 Add to card
  client/src/Components/Cart/ProductCart.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Header/style.css
  client/src/Components/ProductCard/Card.jsx
  client/src/Components/SingleProduct/style.css
  src/controllers/cart/addToCart.js
  src/controllers/cart/getCartByProductId.js
  src/controllers/cart/index.js
  src/controllers/index.js
  src/controllers/product/getProductById.js
  src/controllers/product/index.js
  src/database/queries/cart/getCartByProductId.js
  src/database/queries/cart/index.js
  src/database/queries/index.js
  src/routes/cart.js
  src/routes/product.js
Labels: Approved

#65 63 handle nav
  client/src/App.jsx
  client/src/Components/Error/Error.jsx
  client/src/Components/Error/style.css
  client/src/Components/Header/Header.jsx
  client/src/Components/LandingCard/LandingCard.jsx
  client/src/Components/LandingCard/img/product.png
  client/src/Components/LandingCard/style.css
  client/src/Components/ProductCard/ProductCard.jsx
  client/src/Components/ProductCard/style.css
  client/src/Components/ProductsPage/ProductsPage.jsx
  client/src/Components/ProductsPage/style.css
  client/src/Components/index.jsx
Labels: Await Review

#67 66 fix the add button
  client/.eslintrc.js
  client/src/App.jsx
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/ProductCart.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Login/Login.jsx
  client/src/Components/ProductCard/Card.jsx
  client/src/Components/ProductsPage/ProductsPage.jsx
  client/src/Components/Signup/Singup.jsx
Labels: Await Review

#69 66 fix the add button
  client/src/App.jsx
  client/src/Components/LandingCard/LandingCard.jsx
  client/src/Components/ProductCard/Card.jsx
  client/src/Components/ProductCard/ProductCard.jsx
  client/src/Components/Signup/Singup.jsx
Labels: Await Review
